---
name: Publish AddOn

on:
  workflow_call:
    inputs:
      add_on:
        description: add-on to be published
        required: true
        type: string
    secrets:
      DISPATCH_TOKEN:
        required: true

jobs:      
  publish:
    name: 📢 Publish Add-on
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Dispatch Repository Updater update signal
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: coostax/ha-addons
          event-type: update
          client-payload: '{"addon": "${{ inputs.add_on }}"}'
