---
name: Repository Update

# yamllint disable-line rule:truthy
on:
  workflow_call:
    secrets:
      UPDATER_TOKEN:
        required: true

concurrency:
  group: queue

jobs:
  publish:
    name: Publish add-on update
    runs-on: ubuntu-latest
    steps:
      - name: Set Git Identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
      - name: 🚀 Run Repository Updater
        uses: hassio-addons/repository-updater@v1.3.0
        with:
          addon: ${{ github.event.client_payload.addon }}
          repository: ${{ github.repository }}
          token: ${{ secrets.UPDATER_TOKEN }}
